### ISSUE TITLE
Missing translations of HPO terms omitted in prompts

### ISSUE THREAD

**Issue by leokim-l** [monarch-initiative/phenopacket2prompt#22]
Make sure missing translations of HPO terms are not omitted in non-English prompts. As of now, for instance, a phenopacket with "Short Eyelashes", for which we don´t have an Italian translation, will generate an Italian prompt with a list of observed phenotypes where "Short Eyelashes" is omitted. See

PMID_37179472_Family_3_II_7_en-prompt.txt
PMID_37179472_Family_3_II_7_it-prompt.txt

Maybe have it default to the English term (seems safer) and then check via some test that it actually never happens?

**Comment by pnrobinson** [comment]
I think that we probably need to have the program crash if something is missing. We can either not use genes/phenopackets with missing data or we need to update the translations. I do not think we can use the en word because this could change the performance of the GPT in hard to predict ways!

**Comment by leokim-l** [comment]
Fixed by #54 related to #51, partially reopened as a check in #62
