### ISSUE TITLE
Cannot install, HpInternationalOboParserTest fails

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/phenopacket2prompt#37]
[WARNING] Tests run: 3, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.008 s - in org.monarchinitiative.phenopacket2prompt.international.HpInternationalOboParserTest

<details>

➜  phenopacket2prompt git:(main) ✗ mvn --version
Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)
Maven home: /opt/homebrew/Cellar/maven/3.9.8/libexec
Java version: 22.0.1, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/22.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.6", arch: "aarch64", family: "mac"
➜  phenopacket2prompt git:(main) ✗ mvn test
[INFO] Scanning for projects...
[INFO]
[INFO] --------------< org.monarchinitiative:phenopacket2prompt >--------------
[INFO] Building phenopacket2prompt 0.4.6
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- enforcer:3.3.0:enforce (enforce-maven) @ phenopacket2prompt ---
[INFO] Rule 0: org.apache.maven.enforcer.rules.version.RequireMavenVersion passed
[INFO]
[INFO] --- resources:3.3.0:resources (default-resources) @ phenopacket2prompt ---
[INFO] Copying 1 resource
[INFO]
[INFO] --- compiler:3.8.1:compile (default-compile) @ phenopacket2prompt ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- resources:3.3.0:testResources (default-testResources) @ phenopacket2prompt ---
[INFO] Copying 2 resources
[INFO]
[INFO] --- compiler:3.8.1:testCompile (default-testCompile) @ phenopacket2prompt ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- surefire:3.0.0-M5:test (default-test) @ phenopacket2prompt ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.monarchinitiative.phenopacket2prompt.output.impl.german.PpktIndividualGermanTest
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J(W): Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J(W): Ignoring binding found at [jar:file:/Users/cjm/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.23.1/log4j-slf4j-impl-2.23.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J(W): See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.128 s - in org.monarchinitiative.phenopacket2prompt.output.impl.german.PpktIndividualGermanTest
[INFO] Running org.monarchinitiative.phenopacket2prompt.output.impl.italian.PpktIndividualItalianTest
[WARNING] Tests run: 13, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.015 s - in org.monarchinitiative.phenopacket2prompt.output.impl.italian.PpktIndividualItalianTest
[INFO] Running org.monarchinitiative.phenopacket2prompt.output.impl.english.PPKtEnglishBuildingBlocksTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.monarchinitiative.phenopacket2prompt.output.impl.english.PPKtEnglishBuildingBlocksTest
[INFO] Running org.monarchinitiative.phenopacket2prompt.output.impl.english.PpktPhenotypicFeatureEnglishTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 s - in org.monarchinitiative.phenopacket2prompt.output.impl.english.PpktPhenotypicFeatureEnglishTest
[INFO] Running org.monarchinitiative.phenopacket2prompt.output.impl.english.PpktIndividualEnglishTest
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 s - in org.monarchinitiative.phenopacket2prompt.output.impl.english.PpktIndividualEnglishTest
[INFO] Running org.monarchinitiative.phenopacket2prompt.output.impl.spanish.PpktIndividualSpanishTest
[ERROR] Tests run: 12, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 0.026 s <<< FAILURE! - in org.monarchinitiative.phenopacket2prompt.output.impl.spanish.PpktIndividualSpanishTest
[ERROR] org.monarchinitiative.phenopacket2prompt.output.impl.spanish.PpktIndividualSpanishTest.testEvaluateExpression(TestIndividual)[1]  Time elapsed: 0.004 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Incorrect evaluation for: 46 year olf female, infantile onset ==> expected: <La paciente era una mujer de 46 años que se presentó en el primer año de vida con> but was: <La paciente era una mujer de 46 años. El inicio de la enfermedad ocurrió en la infancia temprana.>
	at org.monarchinitiative.phenopacket2prompt.output.impl.spanish.PpktIndividualSpanishTest.testEvaluateExpression(PpktIndividualSpanishTest.java:45)

[ERROR] org.monarchinitiative.phenopacket2prompt.output.impl.spanish.PpktIndividualSpanishTest.testEvaluateExpression(TestIndividual)[2]  Time elapsed: 0.001 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Incorrect evaluation for: male 4 months, congenital onset ==> expected: <El paciente era un bebé de 4 meses que se presentó al nacer con> but was: <El paciente era un bebé 4 meses. El inicio de la enfermedad ocurrió en el momento del nacimiento.>
	at org.monarchinitiative.phenopacket2prompt.output.impl.spanish.PpktIndividualSpanishTest.testEvaluateExpression(PpktIndividualSpanishTest.java:45)

[ERROR] org.monarchinitiative.phenopacket2prompt.output.impl.spanish.PpktIndividualSpanishTest.testEvaluateExpression(TestIndividual)[3]  Time elapsed: 0.001 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Incorrect evaluation for: female, no onset ==> expected: <La paciente se presentó con> but was: <La paciente era de sexo femenino de edad no especificada. No se indicó la edad del inicio de la enfermedad.>
	at org.monarchinitiative.phenopacket2prompt.output.impl.spanish.PpktIndividualSpanishTest.testEvaluateExpression(PpktIndividualSpanishTest.java:45)

[ERROR] org.monarchinitiative.phenopacket2prompt.output.impl.spanish.PpktIndividualSpanishTest.testEvaluateExpression(TestIndividual)[5]  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Incorrect evaluation for: unknown sex, no 4yo ==> expected: <El paciente se presentó en la niñez con> but was: <El paciente era una persona de sexo y edad no especificados. El inicio de la enfermedad ocurrió en la niñez.>
	at org.monarchinitiative.phenopacket2prompt.output.impl.spanish.PpktIndividualSpanishTest.testEvaluateExpression(PpktIndividualSpanishTest.java:45)

[INFO] Running org.monarchinitiative.phenopacket2prompt.international.HpInternationalOboParserTest
[WARNING] Tests run: 3, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.007 s - in org.monarchinitiative.phenopacket2prompt.international.HpInternationalOboParserTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   PpktIndividualSpanishTest.testEvaluateExpression:45 Incorrect evaluation for: 46 year olf female, infantile onset ==> expected: <La paciente era una mujer de 46 años que se presentó en el primer año de vida con> but was: <La paciente era una mujer de 46 años. El inicio de la enfermedad ocurrió en la infancia temprana.>
[ERROR]   PpktIndividualSpanishTest.testEvaluateExpression:45 Incorrect evaluation for: male 4 months, congenital onset ==> expected: <El paciente era un bebé de 4 meses que se presentó al nacer con> but was: <El paciente era un bebé 4 meses. El inicio de la enfermedad ocurrió en el momento del nacimiento.>
[ERROR]   PpktIndividualSpanishTest.testEvaluateExpression:45 Incorrect evaluation for: female, no onset ==> expected: <La paciente se presentó con> but was: <La paciente era de sexo femenino de edad no especificada. No se indicó la edad del inicio de la enfermedad.>
[ERROR]   PpktIndividualSpanishTest.testEvaluateExpression:45 Incorrect evaluation for: unknown sex, no 4yo ==> expected: <El paciente se presentó en la niñez con> but was: <El paciente era una persona de sexo y edad no especificados. El inicio de la enfermedad ocurrió en la niñez.>
[INFO]
[ERROR] Tests run: 57, Failures: 4, Errors: 0, Skipped: 2
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.580 s
[INFO] Finished at: 2024-06-24T11:14:47-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project phenopacket2prompt: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/cjm/repos/phenopacket2prompt/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

</details>

**Comment by pnrobinson** [comment]
@cmungall 
we are still in a pre-alpha phase with this software, sorry for the crash. 
The issue with this error is that Nico made a few final updates to the format of the hp-international.obo file. 
The tests are working now.
If you have previously downloaded files, please delete the "data" directory and re-run the "download" command, then things should work.
