### ISSUE TITLE
download command also runs testdrive, apparently

### ISSUE THREAD

**Issue by leokim-l** [monarch-initiative/phenopacket2prompt#47]
After deletion of the data/ directory, when running 

`java -jar target/phenopacket2prompt.jar download`

I get

`SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J(W): Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J(W): Ignoring binding found at [jar:file:/Users/leonardo/IdeaProjects/phenopacket2prompt/target/phenopacket2prompt.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J(W): See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
[INFO] Added 9 simulated individuals.
[INFO] Added 18 simulated individuals.
[INFO] Added 27 simulated individuals.
[INFO] Added 36 simulated individuals.
[INFO] Added 45 simulated individuals.
[INFO] Added 54 simulated individuals.
[INFO] Added 63 simulated individuals.
[==================================================]   100%     
[==================================================]   100%  `

(NOTE: judging by the preview of this message, not all newlines of the terminal are correctly represented).

Is this as expected @pnrobinson ?

**Comment by leokim-l** [comment]
Similar behavior with the following, i.e. running the batch command runs also download and testdrive. Which could be a bug or a feature, not sure! (Note copy pasting from terminal does not seem to respect newlines, sorry for the mess)

`leonardo@MBP-GNFWN6C2R7 phenopacket2prompt % java -jar target/phenopacket2prompt.jar batch -d ~/data/phenopacket-store/
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J(W): Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J(W): Ignoring binding found at [jar:file:/Users/leonardo/IdeaProjects/phenopacket2prompt/target/phenopacket2prompt.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J(W): See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
[INFO] Added 9 simulated individuals.
[INFO] Added 18 simulated individuals.
[INFO] Added 27 simulated individuals.
[INFO] Added 36 simulated individuals.
[INFO] Added 45 simulated individuals.
[INFO] Added 54 simulated individuals.
[INFO] Added 63 simulated individuals.
Retrieved 4876 files.
`

**Comment by leokim-l** [comment]
@pnrobinson I understand now the issue. TestDriveCommand has a constructor, at https://github.com/monarch-initiative/phenopacket2prompt/blob/800438507aa702dd200d78201b4fef0d68ab7c67/src/main/java/org/monarchinitiative/phenopacket2prompt/cmd/TestDriveCommand.java#L220-L222 and apparently as a subcommand this is run even if the command is not invoked. This explains why running `download` or `batch` subcommands still outputs things like

`[INFO] Added 27 simulated individuals.`

since the print statement is within the constructor:

https://github.com/monarch-initiative/phenopacket2prompt/blob/800438507aa702dd200d78201b4fef0d68ab7c67/src/main/java/org/monarchinitiative/phenopacket2prompt/cmd/TestDriveCommand.java#L296

Maybe what is now a constructor should be some further class/method, called from within Integer call()..., namely here:

https://github.com/monarch-initiative/phenopacket2prompt/blob/800438507aa702dd200d78201b4fef0d68ab7c67/src/main/java/org/monarchinitiative/phenopacket2prompt/cmd/TestDriveCommand.java#L307

Does this make sense?

**Comment by pnrobinson** [comment]
The problem was that I put some code into the Constructor of the TestDrive command which is a mistake with the picocli framework. I am fixing it.

**Comment by pnrobinson** [comment]
Fixed by https://github.com/monarch-initiative/phenopacket2prompt/pull/53
