### ISSUE TITLE
Manual download of hp.json file

### ISSUE THREAD

**Issue by leokim-l** [monarch-initiative/phenopacket2prompt#48]
Looking at

https://github.com/monarch-initiative/phenopacket2prompt/blob/52c7baa95874c9af35154a50b70a04c895197339/docs/setup.md?plain=1#L23-L25

it seems to suggest hp.json should be manually downloaded. However, it seems to me like 

`java -jar target/phenopacket2prompt.jar download`

does exactly that + downloading hp-international.obo. @pnrobinson is this correct? If so, I can edit the documentation and make a PR

**Comment by pnrobinson** [comment]
The download command does this! The documentation is currently completely out of date, sorry

**Comment by leokim-l** [comment]
Ok, I will edit it and make a PR

**Comment by pnrobinson** [comment]
Fixed by https://github.com/monarch-initiative/phenopacket2prompt/pull/52
