### ISSUE TITLE
Add proper logging

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenopacket2prompt#55]
Probably something like this
https://stackoverflow.com/questions/906233/logging-in-java-and-in-general-best-practices

**Comment by leokim-l** [comment]
Related to #14 , I will do it today

**Comment by leokim-l** [comment]
It's taking more time than expected. In any case, some basis is now here c5d385bef9a5d3dc069c47de0cd7913a44895fa8, should be ready soon

**Comment by leokim-l** [comment]
@pnrobinson what exactly do we want from the logging? Actually, what is there now might be enough, I think. From INFO up, all messages both to file and to terminal. Only need to make it work from the IDE, but this may be IDE related and not an issue with the Java code... Let me know your thoughts!

For future ref., and if someone else wants to tweak configurations, I mainly followed: 
1. Section 4 here: https://www.baeldung.com/java-logging-intro 
2. Section 5-7 of: https://www.baeldung.com/logback

**Comment by leokim-l** [comment]
#57 sets this up, although more may be needed
