### ISSUE TITLE
Standardize start of sentences for unspecified sex and age across languages

### ISSUE THREAD

**Issue by leokim-l** [monarch-initiative/phenopacket2prompt#60]
ex. PMID_33731876_fam151_{lang}-prompt.txt

Spanish:
El paciente era una persona de sexo y edad no especificados.
(The patient was a person of unspecified sex and age)

Dutch:
De proband was een persoon.
(The proband was a person)

English:
The proband was an individual.

@pnrobinson I'd use the Spanish as a ground truth and adapt other languages to that. 
"The proband was an individual" sounds a bit funny...?

**Comment by pnrobinson** [comment]
agree!

**Comment by leokim-l** [comment]
Will do
