### ISSUE TITLE
Merge TUR tests

### ISSUE THREAD

**Issue by aslgraefe** [monarch-initiative/phenopacket2prompt#68]
Doing #59 for Turkish

**Comment by aslgraefe** [comment]
@leokim-l  in there: `/.../git/phenopacket2prompt/src/test/java/org/monarchinitiative/phenopacket2prompt/output/impl`, I could not find any folder 'Turkish' or any files related to Turkish. Could you check please so I can translate the missing bits from (Italian) to Turkish.

**Comment by leokim-l** [comment]
For reference, work happening here https://github.com/monarch-initiative/phenopacket2prompt/tree/68-merge-tur-tests

**Comment by leokim-l** [comment]
What would need to happen here is the creation of a directory `turkish` in here: 
https://github.com/monarch-initiative/phenopacket2prompt/tree/develop/src/test/java/org/monarchinitiative/phenopacket2prompt/output/impl
which contains a class (the one I write here is all we need, unlike what you may see in other languages) PpktIndividualTurkishTest.java which needs to be the Turkish version of this:
https://github.com/monarch-initiative/phenopacket2prompt/blob/develop/src/test/java/org/monarchinitiative/phenopacket2prompt/output/impl/german/PpktIndividualGermanTest.java

If we are then able to compile and package the code without any errors, then we are good to go and finished :)

**Comment by leokim-l** [comment]
#71 fixes this
